#!/bin/bash
# .agent/scripts/rosdep_local_sources.sh
# Generate a workspace-owned rosdep sources.list.d directory that layers every
# project repo's local `rosdep.yaml` on top of the system default sources (#654).
#
# WHY: some Ubuntu-shipped packages have no rosdep key upstream yet. Rather than
# editing /etc (root-owned, invisible to CI, and undoable only by hand), rosdep
# honours ROSDEP_SOURCE_PATH — it REPLACES sources.list.d wholesale, so the
# generated directory must carry a copy of the system lists as well as the local
# ones. Every *.list under the system directory is copied, not just
# 20-default.list: a host may legitimately carry others (10-local.list, a
# site-local overlay), and copying only the default would silently drop a source
# the caller already had.
#
# A project repo opts in by adding a `rosdep.yaml` at ITS OWN ROOT, in upstream
# ros/rosdistro format:
#
#     python3-pystac:          # upstream PR owed: https://github.com/ros/rosdistro/pull/NNNNN
#       ubuntu: [python3-pystac]
#       debian: [python3-pystac]
#
# The comment naming the owed upstream PR is what rosdep_local_staleness_check.sh
# looks for — a local key is always a temporary stand-in for an upstream entry.
#
# This script is deliberately generic: it globs, it never names a repo. The
# `rosdep.yaml` files themselves live in the consuming project repos.
#
# Usage:
#   rosdep_local_sources.sh <workspace_root> [<out_dir>]
#     workspace_root  required — path whose layers/main/*_ws/src/ holds the repos
#     out_dir         optional — default <workspace_root>/.rosdep/sources.list.d
#
# Anchor <workspace_root> at the MAIN workspace root so every worktree on the
# host shares one generated directory (setup.bash resolves it that way).
#
# Callers: bootstrap.sh (step 4), the Makefile's $(STAMP)/rosdep-local.done
# stamp, and anyone regenerating by hand. Consumers read it via
# ROSDEP_SOURCE_PATH, which setup.bash exports when the directory exists.
#
# Prints the number of rosdep.yaml files aggregated. Exit codes:
#   0  generated (including the common zero-rosdep.yaml case — an empty local
#      list is valid, and the system lists are still copied)
#   2  usage error / workspace_root is not a directory
#   3  rosdep is not initialized (no *.list under the system sources dir) —
#      run bootstrap.sh (`sudo rosdep init`) first. Refusing is deliberate: a
#      generated directory holding ONLY the local list would shadow the real
#      default sources and break every rosdep call on the host.

set -euo pipefail

if [[ "${BASH_SOURCE[0]}" != "${0}" ]]; then
    echo "Error: execute this script, don't source it." >&2
    return 1 2>/dev/null || exit 1
fi

SYSTEM_SOURCES_DIR="${ROSDEP_SYSTEM_SOURCES_DIR:-/etc/ros/rosdep/sources.list.d}"

if [ "$#" -lt 1 ] || [ -z "${1:-}" ]; then
    echo "Usage: rosdep_local_sources.sh <workspace_root> [<out_dir>]" >&2
    exit 2
fi

ROOT_DIR="$1"
OUT_DIR="${2:-$ROOT_DIR/.rosdep/sources.list.d}"

if [ ! -d "$ROOT_DIR" ]; then
    echo "Error: workspace_root '$ROOT_DIR' is not a directory." >&2
    exit 2
fi

shopt -s nullglob
system_lists=("$SYSTEM_SOURCES_DIR"/*.list)
if [ "${#system_lists[@]}" -eq 0 ]; then
    echo "Error: no *.list found under $SYSTEM_SOURCES_DIR — rosdep is not initialized." >&2
    echo "       Run .agent/scripts/bootstrap.sh (or: sudo rosdep init) first." >&2
    exit 3
fi

# Rebuild from scratch so a removed repo's entry cannot survive (idempotent).
rm -rf "$OUT_DIR"
mkdir -p "$OUT_DIR"

for list in "${system_lists[@]}"; do
    cp "$list" "$OUT_DIR/$(basename "$list")"
done

# Sorted for determinism: the generated file is compared by the Makefile stamp
# and read by humans; glob order must not churn it.
local_yamls=("$ROOT_DIR"/layers/main/*_ws/src/*/rosdep.yaml)
LOCAL_LIST="$OUT_DIR/30-workspace-local.list"
{
    echo "# Generated by .agent/scripts/rosdep_local_sources.sh — do not edit."
    echo "# One line per project repo carrying a root rosdep.yaml (#654)."
} > "$LOCAL_LIST"

yaml_count=0
if [ "${#local_yamls[@]}" -gt 0 ]; then
    while IFS= read -r yaml; do
        echo "yaml file://$yaml" >> "$LOCAL_LIST"
        yaml_count=$((yaml_count + 1))
    done < <(printf '%s\n' "${local_yamls[@]}" | LC_ALL=C sort)
fi

echo "Aggregated $yaml_count project rosdep.yaml file(s) into $OUT_DIR" \
     "(over ${#system_lists[@]} system source list(s))"
if [ "$yaml_count" -gt 0 ]; then
    echo "Run 'ROSDEP_SOURCE_PATH=$OUT_DIR rosdep update' to refresh the cache."
fi
