#!/bin/bash
# .agent/scripts/worktree_create.sh
# Create a git worktree for isolated task development
#
# Usage:
#   ./worktree_create.sh --issue <number> [--type layer|workspace] [--branch <name>] [--layer <layer_name>] [--packages <pkg,...>] [--plan-file <path>]
#
# Examples:
#   ./worktree_create.sh --issue 123 --type layer --layer core --packages unh_marine_autonomy
#   ./worktree_create.sh --issue 123 --type layer --layer core --packages unh_marine_autonomy,camp
#   ./worktree_create.sh --issue 123 --type workspace
#   ./worktree_create.sh --issue 123 --type workspace --plan-file /tmp/plan.md
#   ./worktree_create.sh --issue 123 --type layer --layer core --packages sonar_driver --plan-file /tmp/plan.md
#   ./worktree_create.sh --skill research --type workspace
#
# Worktree Types:
#   layer     - For ROS package development
#               Created in: layers/worktrees/issue-<N>/
#               Uses hybrid structure for efficiency:
#                 - Git worktrees for packages being modified (--packages)
#                 - Symlinks for other packages in target layer (reuse builds)
#                 - Symlinks for other layers (reuse builds)
#               Requires --layer and --packages
#
#   workspace - For infrastructure work (.agent/, configs/, docs)
#               Created in: .workspace-worktrees/issue-<N>/
#               Full workspace checkout with symlinked layers/
#               No package modification

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(dirname "$(dirname "$SCRIPT_DIR")")"

# Try to fetch a specific branch from origin.
# Returns 0 on successful fetch, non-zero otherwise.
fetch_remote_branch() {
    local git_path="$1"
    local branch="$2"
    git -C "$git_path" fetch --quiet origin -- "$branch" 2>/dev/null
}

# Extract a validated owner/repo slug from a GitHub remote URL.
# Prints the slug on stdout; prints nothing for non-GitHub or malformed URLs.
extract_gh_slug() {
    local url="$1"
    local slug
    slug=$(echo "$url" | sed -E 's#.*github\.com[:/]##' | sed 's/\.git$//')
    if [[ "$slug" =~ ^[^/[:space:]]+/[^/[:space:]]+$ ]]; then
        echo "$slug"
    fi
}

# Resolve the .repos version (branch/tag) for a package name.
# Prints the version on stdout; prints nothing if not found or unknown.
resolve_repos_branch() {
    local pkg_name="$1"
    local version
    version=$(python3 -c "
import sys; sys.path.insert(0, '${SCRIPT_DIR}')
from lib.workspace import find_repo_version
v = find_repo_version('$pkg_name')
if v and v != 'unknown': print(v)
" 2>/dev/null)
    if [ -n "$version" ]; then
        echo "$version"
    fi
}

# Generate convenience scripts for layer worktrees.
# Creates setup.bash, build.sh, test.sh, and colcon/defaults.yaml in the
# layer worktree so users can build and test without knowing about
# worktree_enter.sh or ROS2_LAYERS_BASE.
generate_worktree_scripts() {
    local wt_dir="$1"
    local main_root="$2"

    echo ""
    echo "Generating convenience scripts..."

    # Resolve layers config (same logic as setup.bash lines 57-81)
    local layers_config="$main_root/configs/manifest/layers.txt"
    local layers=()
    if [ -f "$layers_config" ]; then
        mapfile -t layers < <(grep -v '^[[:space:]]*$' "$layers_config" | grep -v '^#')
    else
        layers=("${AVAILABLE_LAYERS[@]}")
    fi

    # --- setup.bash ---
    cat > "$wt_dir/setup.bash" << 'SETUP_HEADER'
#!/bin/bash
# Generated by worktree_create.sh — sets up the ROS 2 environment for this worktree.
# Usage: source setup.bash

# 1. Base ROS 2 Environment
if [ -f "/opt/ros/jazzy/setup.bash" ]; then
    source /opt/ros/jazzy/setup.bash
else
    echo "  ! Error: /opt/ros/jazzy/setup.bash not found. Please install ROS 2 Jazzy."
    return 1 2>/dev/null || exit 1
fi

SETUP_HEADER

    # Worktree-specific variables (written with values resolved at generation time)
    # Use printf %q to safely handle paths with spaces or shell metacharacters
    echo "# Worktree identity" >> "$wt_dir/setup.bash"
    printf 'WORKTREE_DIR=%q\n' "$wt_dir" >> "$wt_dir/setup.bash"

    if [ -n "$ISSUE_NUM" ]; then
        printf 'export WORKTREE_ISSUE=%q\n' "$ISSUE_NUM" >> "$wt_dir/setup.bash"
    fi
    if [ -n "$SKILL_NAME" ]; then
        printf 'export WORKTREE_SKILL=%q\n' "$SKILL_NAME" >> "$wt_dir/setup.bash"
    fi
    if [ -n "$PARENT_ISSUE_NUM" ]; then
        printf 'export WORKTREE_PARENT_ISSUE=%q\n' "$PARENT_ISSUE_NUM" >> "$wt_dir/setup.bash"
    fi

    cat >> "$wt_dir/setup.bash" << 'SETUP_VARS2'
export WORKTREE_TYPE="layer"
export WORKTREE_ROOT="$WORKTREE_DIR"
export ROS2_LAYERS_BASE="$WORKTREE_DIR"
SETUP_VARS2
    printf 'export ROS2_WORKSPACE_ROOT=%q\n\n' "$main_root" >> "$wt_dir/setup.bash"

    # Source each layer's install/setup.bash
    cat >> "$wt_dir/setup.bash" << 'SETUP_LAYERS_HEADER'
# 2. Source workspace layers
echo "Sourcing ROS2 Agent Workspace layers..."
SETUP_LAYERS_HEADER

    for layer in "${layers[@]}"; do
        cat >> "$wt_dir/setup.bash" << SETUP_LAYER
if [ -f "\$WORKTREE_DIR/${layer}_ws/install/setup.bash" ]; then
    echo "  - Sourcing ${layer}..."
    source "\$WORKTREE_DIR/${layer}_ws/install/setup.bash"
elif [ -d "\$WORKTREE_DIR/${layer}_ws/src" ]; then
    echo "  ! Warning: ${layer} exists but is not built."
fi
SETUP_LAYER
    done

    # Git checkout guardrail + GIT_EDITOR + pre-commit
    cat >> "$wt_dir/setup.bash" << SETUP_FOOTER

# 3. Guard against branch switching
git() {
    if [[ "\${1:-}" == "checkout" ]]; then
        if [[ "\${2:-}" == "--" || "\${2:-}" == "-p" ]]; then
            command git "\$@"
            return \$?
        fi
        echo "❌ 'git checkout' for branch switching is disabled in this workspace."
        echo "   Use worktrees instead."
        echo "   To restore files, use: git checkout -- <file>"
        return 1
    fi
    command git "\$@"
}

# 4. Expose pre-commit from .venv
SETUP_FOOTER

    # Emit pre-commit path safely (printf %q handles spaces/metacharacters)
    local _escaped_main_root
    printf -v _escaped_main_root '%q' "$main_root"
    cat >> "$wt_dir/setup.bash" << SETUP_PRECOMMIT
if [ -x ${_escaped_main_root}/.venv/bin/pre-commit ]; then
    pre-commit() { ${_escaped_main_root}/.venv/bin/pre-commit "\$@"; }
fi
SETUP_PRECOMMIT

    cat >> "$wt_dir/setup.bash" << 'SETUP_FOOTER2'

# 5. Prevent interactive editor hangs
export GIT_EDITOR=true

echo "Environment ready."
SETUP_FOOTER2

    echo "  ✓ setup.bash"

    # --- Per-layer build.sh, test.sh, colcon/defaults.yaml ---
    for layer in "${layers[@]}"; do
        local layer_ws="${layer}_ws"
        local layer_dir="$wt_dir/$layer_ws"

        # Skip symlinked layers — writing into them would modify the shared
        # main workspace and embed worktree-specific paths in shared files.
        if [ -L "$layer_dir" ]; then
            continue
        fi

        # Only generate for layers that have a src/ directory
        if [ ! -d "$layer_dir/src" ]; then
            continue
        fi

        # --- colcon/defaults.yaml ---
        # colcon auto-discovers defaults.yaml from $PWD/colcon/defaults.yaml
        # (build.sh cd's into the layer_ws first)
        mkdir -p "$layer_dir/colcon"
        cat > "$layer_dir/colcon/defaults.yaml" << 'COLCON_DEFAULTS'
build:
  symlink-install: true
  cmake-args:
    - -DCMAKE_EXPORT_COMPILE_COMMANDS=ON
test:
  {}
COLCON_DEFAULTS
        echo "  ✓ $layer_ws/colcon/defaults.yaml"

        # Build the sourcing preamble for this layer's scripts:
        # source /opt/ros/jazzy/setup.bash, then all layers BEFORE this one
        local preamble=""
        preamble+="if [ -f /opt/ros/jazzy/setup.bash ]; then"$'\n'
        preamble+="    source /opt/ros/jazzy/setup.bash"$'\n'
        preamble+="else"$'\n'
        preamble+="    echo \"ERROR: /opt/ros/jazzy/setup.bash not found. Please install ROS 2 Jazzy.\" 1>&2"$'\n'
        preamble+="    exit 1"$'\n'
        preamble+="fi"$'\n'
        for prev_layer in "${layers[@]}"; do
            if [ "$prev_layer" == "$layer" ]; then
                break
            fi
            preamble+="if [ -f \"$wt_dir/${prev_layer}_ws/install/setup.bash\" ]; then"$'\n'
            preamble+="    source \"$wt_dir/${prev_layer}_ws/install/setup.bash\""$'\n'
            preamble+="fi"$'\n'
        done

        # Collect expected AMENT_PREFIX_PATH entries for validation
        local expected_prefixes=()
        for prev_layer in "${layers[@]}"; do
            if [ "$prev_layer" == "$layer" ]; then
                break
            fi
            expected_prefixes+=("${prev_layer}_ws/install")
        done

        # --- build.sh ---
        cat > "$layer_dir/build.sh" << BUILDSH
#!/bin/bash
# Generated by worktree_create.sh — build the $layer layer.
# Usage: ./build.sh [package ...]
set -e
cd "\$(dirname "\$0")"

# Source ROS 2 base and lower layers
$preamble
BUILDSH

        # Add AMENT_PREFIX_PATH validation if there are lower layers
        if [ ${#expected_prefixes[@]} -gt 0 ]; then
            for ep in "${expected_prefixes[@]}"; do
                cat >> "$layer_dir/build.sh" << BUILDSH_VALIDATE
# Validate lower layers are sourced
if [ -n "\${AMENT_PREFIX_PATH:-}" ] && [[ "\$AMENT_PREFIX_PATH" != *"$ep"* ]]; then
    echo "  ⚠  Warning: $ep not found in AMENT_PREFIX_PATH"
fi
BUILDSH_VALIDATE
            done
            echo "" >> "$layer_dir/build.sh"
        fi

        cat >> "$layer_dir/build.sh" << 'BUILDSH_BUILD'
# Build
if [ $# -gt 0 ]; then
    colcon build --packages-select "$@"
else
    colcon build
fi
BUILDSH_BUILD
        chmod +x "$layer_dir/build.sh"
        echo "  ✓ $layer_ws/build.sh"

        # --- test.sh ---
        cat > "$layer_dir/test.sh" << TESTSH
#!/bin/bash
# Generated by worktree_create.sh — test the $layer layer.
# Usage: ./test.sh [package ...]
set -e
cd "\$(dirname "\$0")"

# Source ROS 2 base and lower layers
$preamble
TESTSH

        cat >> "$layer_dir/test.sh" << 'TESTSH_TEST'
# Test (capture exit code so colcon test-result always runs)
test_exit_code=0
if [ $# -gt 0 ]; then
    colcon test --return-code-on-test-failure --packages-select "$@" || test_exit_code=$?
else
    colcon test --return-code-on-test-failure || test_exit_code=$?
fi
colcon test-result --verbose || true
exit "$test_exit_code"
TESTSH_TEST
        chmod +x "$layer_dir/test.sh"
        echo "  ✓ $layer_ws/test.sh"
    done
}

# Defaults
ISSUE_NUM=""
SKILL_NAME=""       # Skill name (alternative to --issue)
WORKTREE_TYPE="layer"
BRANCH_NAME=""
TARGET_LAYER=""
REPO_SLUG=""
TARGET_PACKAGES=""  # Comma-separated list of packages to modify
PLAN_FILE=""        # Path to approved plan file (implies draft PR creation)
PARENT_ISSUE_NUM="" # Parent issue number for sub-issue worktrees

# Skills allowed to create worktrees without a GitHub issue
ALLOWED_SKILLS=("research" "inspiration-tracker")

# Available layers — read from manifest; exit if not found.
# ROOT_DIR is derived from BASH_SOURCE and may resolve into a worktree
# (e.g., when invoked via a symlink from .workspace-worktrees/ or
# layers/worktrees/) where configs/ doesn't exist. Search parent
# directories to find the main workspace root:
#   depth 2: .workspace-worktrees/issue-workspace-N -> main root
#   depth 3: layers/worktrees/issue-repo-N -> main root
_LAYERS_CONFIG="$ROOT_DIR/configs/manifest/layers.txt"
if [ ! -f "$_LAYERS_CONFIG" ]; then
    for _depth in 2 3; do
        _main_root="$ROOT_DIR"
        for (( _i=0; _i<_depth; _i++ )); do _main_root="$(dirname "$_main_root")"; done
        if [ -f "$_main_root/configs/manifest/layers.txt" ]; then
            _LAYERS_CONFIG="$_main_root/configs/manifest/layers.txt"
            break
        fi
    done
fi
if [ -f "$_LAYERS_CONFIG" ]; then
    mapfile -t AVAILABLE_LAYERS < <(grep -v '^[[:space:]]*$' "$_LAYERS_CONFIG" | grep -v '^#' | sed 's/[[:space:]]*$//')
else
    echo "Error: Layer config not found."
    echo "Expected layer manifest at: $_LAYERS_CONFIG"
    echo "ROOT_DIR was: $ROOT_DIR"
    echo "Run 'make build' to set up the workspace first."
    exit 1
fi
if [ ${#AVAILABLE_LAYERS[@]} -eq 0 ]; then
    echo "Error: No layers found in $_LAYERS_CONFIG"
    exit 1
fi

show_usage() {
    echo "Usage: $0 (--issue <number> | --skill <name>) --type <layer|workspace> [options]"
    echo ""
    echo "Options:"
    echo "  --issue <number>      Issue number (required, unless --skill is used)"
    echo "  --skill <name>        Skill name (alternative to --issue; allowed: ${ALLOWED_SKILLS[*]})"
    echo "  --type <type>         Worktree type: 'layer' or 'workspace' (required)"
    echo "  --layer <name>        Layer to work on (required for layer type)"
    echo "                        Available: ${AVAILABLE_LAYERS[*]}"
    echo "  --packages <pkg,...>  Package(s) to modify (required for layer type)"
    echo "                        Comma-separated list for multiple packages"
    echo "  --repo-slug <slug>    Repository slug for naming (auto-detected if not provided)"
    echo "  --branch <name>       Custom branch name (default: feature/issue-<N> or skill/<id>)"
    echo "  --parent-issue <N>    Parent issue number; branches from parent's feature branch and targets PR at it"
    echo "  --plan-file <path>    Path to approved plan file; creates draft PR and posts plan as comment"
    echo ""
    echo "Examples:"
    echo "  $0 --issue 123 --type layer --layer core --packages unh_marine_autonomy"
    echo "  $0 --issue 123 --type layer --layer core --packages unh_marine_autonomy,camp"
    echo "  $0 --issue 123 --type workspace"
    echo "  $0 --skill research --type workspace"
    echo "  $0 --issue 5 --type layer --layer sensors --packages sonar_driver --repo-slug marine_msgs"
}

# Parse arguments
while [[ $# -gt 0 ]]; do
    case $1 in
        --issue)
            ISSUE_NUM="$2"
            shift 2
            ;;
        --skill)
            if [[ -z "${2:-}" || "$2" == -* ]]; then
                echo "Error: --skill requires a skill name"
                show_usage
                exit 1
            fi
            SKILL_NAME="$2"
            shift 2
            ;;
        --type)
            WORKTREE_TYPE="$2"
            shift 2
            ;;
        --layer)
            TARGET_LAYER="$2"
            shift 2
            ;;
        --repo-slug)
            REPO_SLUG="$2"
            shift 2
            ;;
        --branch)
            BRANCH_NAME="$2"
            shift 2
            ;;
        --packages)
            TARGET_PACKAGES="$2"
            shift 2
            ;;
        --parent-issue)
            if [[ -z "${2:-}" || "$2" == -* ]]; then
                echo "Error: --parent-issue requires an issue number"
                show_usage
                exit 1
            fi
            if ! [[ "$2" =~ ^[0-9]+$ ]]; then
                echo "Error: --parent-issue value must be a number, got '$2'"
                exit 1
            fi
            PARENT_ISSUE_NUM="$2"
            shift 2
            ;;
        --plan-file)
            PLAN_FILE="$2"
            shift 2
            ;;
        -h|--help)
            show_usage
            exit 0
            ;;
        *)
            echo "Error: Unknown option $1"
            show_usage
            exit 1
            ;;
    esac
done

# Validate required arguments: --issue XOR --skill
if [ -n "$ISSUE_NUM" ] && [ -n "$SKILL_NAME" ]; then
    echo "Error: --issue and --skill are mutually exclusive"
    show_usage
    exit 1
fi
if [ -z "$ISSUE_NUM" ] && [ -z "$SKILL_NAME" ]; then
    echo "Error: either --issue or --skill is required"
    show_usage
    exit 1
fi
if [ -n "$SKILL_NAME" ] && [ -n "$PARENT_ISSUE_NUM" ]; then
    echo "Error: --parent-issue cannot be used with --skill (skills have no parent issue)"
    exit 1
fi

# Validate skill name against allowlist
if [ -n "$SKILL_NAME" ]; then
    VALID_SKILL=false
    for allowed in "${ALLOWED_SKILLS[@]}"; do
        if [ "$allowed" == "$SKILL_NAME" ]; then
            VALID_SKILL=true
            break
        fi
    done
    if [ "$VALID_SKILL" = false ]; then
        echo "Error: Skill '$SKILL_NAME' is not in the allowlist"
        echo "Allowed skills: ${ALLOWED_SKILLS[*]}"
        exit 1
    fi
    # Generate synthetic ID with timestamp + collision-resistant suffix
    # %N is GNU-specific (nanoseconds); on BSD/macOS it outputs literal "N"
    _SKILL_TS=$(date +"%Y%m%d-%H%M%S")
    _SKILL_NANO=$(date +"%N" 2>/dev/null)
    if [ -z "$_SKILL_NANO" ] || [ "$_SKILL_NANO" = "N" ] || [ "$_SKILL_NANO" = "%N" ]; then
        # Fallback: use $RANDOM (0-32767) for uniqueness on non-GNU systems
        _SKILL_NANO=$RANDOM
    fi
    SYNTHETIC_ID="${SKILL_NAME}-${_SKILL_TS}-${_SKILL_NANO}"
    unset _SKILL_TS _SKILL_NANO
fi

# Validate worktree type
if [ "$WORKTREE_TYPE" != "layer" ] && [ "$WORKTREE_TYPE" != "workspace" ]; then
    echo "Error: --type must be 'layer' or 'workspace'"
    exit 1
fi

# For layer worktrees, require --layer and --packages
if [ "$WORKTREE_TYPE" == "layer" ]; then
    if [ -z "$TARGET_LAYER" ]; then
        echo "Error: --layer is required for layer worktrees"
        echo "Available layers: ${AVAILABLE_LAYERS[*]}"
        exit 1
    fi
    if [ -z "$TARGET_PACKAGES" ]; then
        echo "Error: --packages is required for layer worktrees"
        echo "Example: --packages unh_marine_autonomy"
        echo "         --packages unh_marine_autonomy,camp  (for multiple)"
        exit 1
    fi
fi

# Validate layer name if provided
if [ -n "$TARGET_LAYER" ]; then
    VALID_LAYER=false
    for layer in "${AVAILABLE_LAYERS[@]}"; do
        if [ "$layer" == "$TARGET_LAYER" ]; then
            VALID_LAYER=true
            break
        fi
    done
    if [ "$VALID_LAYER" = false ]; then
        echo "Error: Invalid layer '$TARGET_LAYER'"
        echo "Available layers: ${AVAILABLE_LAYERS[*]}"
        exit 1
    fi
fi

# Auto-detect repo slug if not provided
if [ -z "$REPO_SLUG" ]; then
    REMOTE_URL=""

    # For layer worktrees, detect slug from the first package's git remote
    # (the issue typically lives in the same repo as the package being modified)
    if [ "$WORKTREE_TYPE" == "layer" ] && [ -n "$TARGET_PACKAGES" ]; then
        # Extract first package name from comma-separated list
        FIRST_PKG="${TARGET_PACKAGES%%,*}"
        # Trim whitespace
        FIRST_PKG="${FIRST_PKG#"${FIRST_PKG%%[![:space:]]*}"}"
        FIRST_PKG="${FIRST_PKG%"${FIRST_PKG##*[![:space:]]}"}"

        PKG_PATH="$ROOT_DIR/layers/main/${TARGET_LAYER}_ws/src/$FIRST_PKG"
        if [ -d "$PKG_PATH" ] && git -C "$PKG_PATH" remote get-url origin &>/dev/null; then
            REMOTE_URL=$(git -C "$PKG_PATH" remote get-url origin)
        fi
    fi

    # Fallback: detect from workspace repo remote (use -C to ensure we
    # always query the workspace repo, regardless of the caller's cwd)
    if [ -z "$REMOTE_URL" ]; then
        if git -C "$ROOT_DIR" remote get-url origin &>/dev/null; then
            REMOTE_URL=$(git -C "$ROOT_DIR" remote get-url origin)
        fi
    fi

    if [ -n "$REMOTE_URL" ]; then
        # Extract owner/repo slug for GitHub CLI (e.g., "org/repo")
        GH_REPO_SLUG=$(extract_gh_slug "$REMOTE_URL")

        # Extract repo name from URL (works for both HTTPS and SSH)
        # e.g., https://github.com/org/repo.git -> repo
        # e.g., git@github.com:org/repo.git -> repo
        REPO_SLUG=$(basename "$REMOTE_URL" .git)

        # If this is the main workspace repo, use "workspace" as the slug
        if [ "$REPO_SLUG" == "ros2_agent_workspace" ]; then
            REPO_SLUG="workspace"
        fi

        # Sanitize repo slug: replace hyphens and other invalid characters with underscores
        REPO_SLUG=$(echo "$REPO_SLUG" | sed 's/[^A-Za-z0-9_]/_/g')
    else
        # Fallback to "workspace" if no remote detected
        GH_REPO_SLUG=""
        REPO_SLUG="workspace"
    fi
    echo "Auto-detected repository slug: $REPO_SLUG"
else
    # --repo-slug controls worktree naming; still auto-detect GH_REPO_SLUG
    # for GitHub API calls (gh issue view, etc.)
    GH_REPO_SLUG=""
    if [ "$WORKTREE_TYPE" == "layer" ] && [ -n "$TARGET_PACKAGES" ]; then
        FIRST_PKG="${TARGET_PACKAGES%%,*}"
        FIRST_PKG="${FIRST_PKG#"${FIRST_PKG%%[![:space:]]*}"}"
        FIRST_PKG="${FIRST_PKG%"${FIRST_PKG##*[![:space:]]}"}"
        PKG_PATH="$ROOT_DIR/layers/main/${TARGET_LAYER}_ws/src/$FIRST_PKG"
        if [ -d "$PKG_PATH" ] && git -C "$PKG_PATH" remote get-url origin &>/dev/null; then
            REMOTE_URL=$(git -C "$PKG_PATH" remote get-url origin)
            GH_REPO_SLUG=$(extract_gh_slug "$REMOTE_URL")
        fi
    elif git -C "$ROOT_DIR" remote get-url origin &>/dev/null; then
        REMOTE_URL=$(git -C "$ROOT_DIR" remote get-url origin)
        GH_REPO_SLUG=$(extract_gh_slug "$REMOTE_URL")
    fi
    REPO_SLUG=$(echo "$REPO_SLUG" | sed 's/[^A-Za-z0-9_]/_/g')
fi

# Validate issue exists and fetch title (after GH_REPO_SLUG is resolved)
# Skip in skill mode — there is no issue to validate
ISSUE_TITLE=""
ISSUE_STATE=""
if [ -n "$ISSUE_NUM" ]; then
    # Try git-bug first for issue title and state (offline-capable)
    if command -v git-bug &>/dev/null; then
        _BUG_OUTPUT=$(git -C "$ROOT_DIR" bug select "$ISSUE_NUM" 2>/dev/null \
            && git -C "$ROOT_DIR" bug show 2>/dev/null || echo "")
        if [ -n "$_BUG_OUTPUT" ]; then
            _BUG_TITLE=$(echo "$_BUG_OUTPUT" | head -1 | sed 's/^[^ ]* //')
            _BUG_STATE=$(echo "$_BUG_OUTPUT" | grep -i '^status:' | awk '{print $2}' || echo "")
            if [ -n "$_BUG_TITLE" ]; then
                ISSUE_TITLE="$_BUG_TITLE"
                [[ "${_BUG_STATE,,}" == "closed" ]] && ISSUE_STATE="CLOSED"
                [[ "${_BUG_STATE,,}" == "open" ]] && ISSUE_STATE="OPEN"
            fi
        fi
        git -C "$ROOT_DIR" bug deselect 2>/dev/null || true
    fi

    if command -v gh &>/dev/null; then
        # PR check stays gh-only — git-bug doesn't track PRs
        _PR_CHECK=""
        if [ -n "$GH_REPO_SLUG" ]; then
            _PR_CHECK=$(gh pr view "$ISSUE_NUM" --repo "$GH_REPO_SLUG" --json state --jq '.state' 2>/dev/null || echo "")
        else
            _PR_CHECK=$(gh pr view "$ISSUE_NUM" --json state --jq '.state' 2>/dev/null || echo "")
        fi
        if [ -n "$_PR_CHECK" ]; then
            echo "Error: #$ISSUE_NUM is a pull request, not an issue."
            echo "Use the original issue number instead."
            exit 1
        fi

        # Fall back to gh for title/state if git-bug didn't provide them
        if [ -z "$ISSUE_TITLE" ] || [ -z "$ISSUE_STATE" ]; then
            if [ -n "$GH_REPO_SLUG" ]; then
                _ISSUE_INFO=$(gh issue view "$ISSUE_NUM" --repo "$GH_REPO_SLUG" --json title,state --jq '.title + "||" + .state' 2>/dev/null || echo "")
            else
                _ISSUE_INFO=$(gh issue view "$ISSUE_NUM" --json title,state --jq '.title + "||" + .state' 2>/dev/null || echo "")
            fi
            if [[ "$_ISSUE_INFO" == *"||"* ]]; then
                ISSUE_TITLE="${_ISSUE_INFO%||*}"
                ISSUE_STATE="${_ISSUE_INFO##*||}"
            fi
        fi
    fi
    if [ -n "$ISSUE_TITLE" ]; then
        echo "Issue #$ISSUE_NUM: $ISSUE_TITLE"
        if [ "$ISSUE_STATE" = "CLOSED" ]; then
            echo "   ⚠️  Warning: Issue #$ISSUE_NUM is CLOSED"
        fi
    else
        echo "⚠️  Could not fetch issue #$ISSUE_NUM title (offline or issue does not exist)"
        echo "   Proceeding anyway — verify the issue number is correct."
    fi
else
    echo "Skill worktree: $SKILL_NAME (ID: $SYNTHETIC_ID)"
fi
echo ""

# Set default branch name if not provided
if [ -z "$BRANCH_NAME" ]; then
    if [ -n "$SKILL_NAME" ]; then
        BRANCH_NAME="skill/${SYNTHETIC_ID}"
    else
        BRANCH_NAME="feature/issue-${ISSUE_NUM}"
    fi
fi

# Derive parent branch name from --parent-issue
PARENT_BRANCH=""
if [ -n "$PARENT_ISSUE_NUM" ]; then
    PARENT_BRANCH="feature/issue-${PARENT_ISSUE_NUM}"
fi

# Determine worktree path based on type and mode (issue vs skill)
if [ -n "$SKILL_NAME" ]; then
    DIR_PREFIX="skill-${REPO_SLUG}-${SYNTHETIC_ID}"
else
    DIR_PREFIX="issue-${REPO_SLUG}-${ISSUE_NUM}"
fi
if [ "$WORKTREE_TYPE" == "layer" ]; then
    WORKTREE_DIR="$ROOT_DIR/layers/worktrees/${DIR_PREFIX}"
else
    WORKTREE_DIR="$ROOT_DIR/.workspace-worktrees/${DIR_PREFIX}"
fi

# Check if worktree already exists
if [ -d "$WORKTREE_DIR" ]; then
    echo "Error: Worktree already exists at $WORKTREE_DIR"
    if [ -n "$SKILL_NAME" ]; then
        echo "Use 'worktree_enter.sh --skill $SKILL_NAME' to enter it"
        echo "Or 'worktree_remove.sh --skill $SKILL_NAME' to remove it"
    else
        echo "Use 'worktree_enter.sh --issue $ISSUE_NUM' to enter it"
        echo "Or 'worktree_remove.sh --issue $ISSUE_NUM' to remove it"
    fi
    exit 1
fi

cd "$ROOT_DIR"

echo "========================================"
echo "Creating Worktree"
echo "========================================"
if [ -n "$SKILL_NAME" ]; then
    echo "  Skill:      $SKILL_NAME"
    echo "  ID:         $SYNTHETIC_ID"
else
    echo "  Issue:      #$ISSUE_NUM"
fi
echo "  Repository: $REPO_SLUG"
echo "  Type:       $WORKTREE_TYPE"
[ -n "$TARGET_LAYER" ] && echo "  Layer:      $TARGET_LAYER"
echo "  Branch:     $BRANCH_NAME"
[ -n "$PARENT_BRANCH" ] && echo "  Parent:     #$PARENT_ISSUE_NUM ($PARENT_BRANCH)"
echo "  Path:       $WORKTREE_DIR"
echo ""

# Create parent directory if needed
mkdir -p "$(dirname "$WORKTREE_DIR")"

# Track whether parent branch was actually used (guards PR --base later)
PARENT_BRANCH_FOUND=false

# Create the worktree directory
if [ "$WORKTREE_TYPE" == "workspace" ]; then
    # Workspace worktrees are full git worktrees of the workspace repo
    if git show-ref --verify --quiet "refs/heads/$BRANCH_NAME"; then
        echo "Using existing local branch '$BRANCH_NAME'..."
        git worktree add "$WORKTREE_DIR" "$BRANCH_NAME"
    elif fetch_remote_branch "$ROOT_DIR" "$BRANCH_NAME"; then
        echo "Tracking remote branch 'origin/$BRANCH_NAME'..."
        git worktree add --track -b "$BRANCH_NAME" "$WORKTREE_DIR" "origin/$BRANCH_NAME"
    elif [ -n "$PARENT_BRANCH" ]; then
        # Branch from parent issue's feature branch
        if git show-ref --verify --quiet "refs/heads/$PARENT_BRANCH"; then
            echo "Creating new branch '$BRANCH_NAME' from parent branch '$PARENT_BRANCH'..."
            git worktree add -b "$BRANCH_NAME" "$WORKTREE_DIR" "$PARENT_BRANCH"
            PARENT_BRANCH_FOUND=true
        elif fetch_remote_branch "$ROOT_DIR" "$PARENT_BRANCH"; then
            echo "Creating new branch '$BRANCH_NAME' from parent branch 'origin/$PARENT_BRANCH'..."
            git worktree add -b "$BRANCH_NAME" "$WORKTREE_DIR" "origin/$PARENT_BRANCH"
            PARENT_BRANCH_FOUND=true
        else
            echo "⚠️  Parent branch '$PARENT_BRANCH' not found; falling back to HEAD"
            git worktree add -b "$BRANCH_NAME" "$WORKTREE_DIR"
        fi
    else
        echo "Creating new branch '$BRANCH_NAME' from current HEAD..."
        git worktree add -b "$BRANCH_NAME" "$WORKTREE_DIR"
    fi

    # If child branch already existed and --parent-issue was given, probe parent
    # branch existence so draft PR can still target it (stacked PR).
    if [ -n "$PARENT_BRANCH" ] && [ "$PARENT_BRANCH_FOUND" = false ]; then
        if git show-ref --verify --quiet "refs/heads/$PARENT_BRANCH" || \
           git show-ref --verify --quiet "refs/remotes/origin/$PARENT_BRANCH"; then
            PARENT_BRANCH_FOUND=true
        elif fetch_remote_branch "$ROOT_DIR" "$PARENT_BRANCH" && \
             git show-ref --verify --quiet "refs/remotes/origin/$PARENT_BRANCH"; then
            PARENT_BRANCH_FOUND=true
        fi
    fi
else
    # Layer worktrees are plain directories containing per-package git worktrees.
    # The branch is created in the individual package repos, not the workspace repo.
    mkdir -p "$WORKTREE_DIR"
fi

# For layer worktrees, set up the layer structure with symlinks
if [ "$WORKTREE_TYPE" == "layer" ]; then
    echo ""
    echo "Setting up layer worktree structure..."

    # Create scratchpad for this worktree
    mkdir -p "$WORKTREE_DIR/.scratchpad"
    if [ -n "$SKILL_NAME" ]; then
        cat > "$WORKTREE_DIR/.scratchpad/README.md" << EOF
# Task Scratchpad for Skill: $SKILL_NAME ($SYNTHETIC_ID)

This directory is for temporary files specific to this task.
Files here are gitignored and isolated from other worktrees.

**Working layer**: ${TARGET_LAYER}_ws
EOF
    else
        cat > "$WORKTREE_DIR/.scratchpad/README.md" << EOF
# Task Scratchpad for Issue #$ISSUE_NUM

This directory is for temporary files specific to this task.
Files here are gitignored and isolated from other worktrees.

**Working layer**: ${TARGET_LAYER}_ws
EOF
    fi

    # Persist parent issue for worktree_enter.sh to pick up
    if [ -n "$PARENT_ISSUE_NUM" ]; then
        echo "$PARENT_ISSUE_NUM" > "$WORKTREE_DIR/.scratchpad/.parent_issue"
    fi

    # Create symlinks to main for all layers except target
    echo "Creating symlinks to main layers..."
    for layer in "${AVAILABLE_LAYERS[@]}"; do
        LAYER_WS="${layer}_ws"
        if [ "$layer" == "$TARGET_LAYER" ]; then
            # Target layer - create hybrid structure: git worktrees for modified packages, symlinks for others
            echo "  - $LAYER_WS: creating hybrid structure (git worktrees + symlinks)"
            mkdir -p "$WORKTREE_DIR/${LAYER_WS}/src"

            # Convert comma-separated packages to array without permanently changing IFS
            OLD_IFS=$IFS
            IFS=','
            # Read raw entries, then trim whitespace from each package name
            read -ra RAW_PACKAGE_ARRAY <<< "$TARGET_PACKAGES"
            IFS=$OLD_IFS

            PACKAGE_ARRAY=()
            for raw_pkg in "${RAW_PACKAGE_ARRAY[@]}"; do
                # Trim leading and trailing whitespace
                pkg="${raw_pkg#"${raw_pkg%%[![:space:]]*}"}"
                pkg="${pkg%"${pkg##*[![:space:]]}"}"
                # Skip empty entries (e.g., from ",,")
                if [ -n "$pkg" ]; then
                    PACKAGE_ARRAY+=("$pkg")
                fi
            done

            # Get list of all packages in main layer
            MAIN_SRC_DIR="$ROOT_DIR/layers/main/${LAYER_WS}/src"
            if [ ! -d "$MAIN_SRC_DIR" ]; then
                echo "    Error: Layer directory not found: $MAIN_SRC_DIR"
                exit 1
            fi

            # Process each package in main
            for pkg_path in "$MAIN_SRC_DIR"/*; do
                if [ ! -d "$pkg_path" ]; then
                    continue
                fi

                pkg_name=$(basename "$pkg_path")

                # Check if this package should have a worktree
                CREATE_WORKTREE=false
                for target_pkg in "${PACKAGE_ARRAY[@]}"; do
                    if [ "$pkg_name" == "$target_pkg" ]; then
                        CREATE_WORKTREE=true
                        break
                    fi
                done

                if [ "$CREATE_WORKTREE" = true ]; then
                    # Create git worktree for this package
                    echo "    - $pkg_name: creating git worktree (modified)"

                    # Check if package is a git repository
                    if [ -d "$pkg_path/.git" ]; then
                        # Create worktree from this package's git repo
                        cd "$pkg_path"
                        WORKTREE_PKG_PATH="$WORKTREE_DIR/${LAYER_WS}/src/$pkg_name"

                        # Resolve the .repos base branch for this package
                        REPOS_BRANCH=$(resolve_repos_branch "$pkg_name")
                        if [ -n "$REPOS_BRANCH" ]; then
                            git fetch --quiet origin "$REPOS_BRANCH" 2>/dev/null || true
                        fi

                        # Fetch parent branch if specified
                        if [ -n "$PARENT_BRANCH" ]; then
                            fetch_remote_branch "$pkg_path" "$PARENT_BRANCH" || true
                        fi

                        # Prefer the issue branch for this package: local first, then remote, then parent branch, then .repos branch, then HEAD
                        if git worktree add "$WORKTREE_PKG_PATH" "$BRANCH_NAME" 2>/dev/null; then
                            echo "      ✓ Worktree created from existing local branch: $BRANCH_NAME"
                        elif fetch_remote_branch "$pkg_path" "$BRANCH_NAME" && \
                             git worktree add --track -b "$BRANCH_NAME" "$WORKTREE_PKG_PATH" "origin/$BRANCH_NAME" 2>/dev/null; then
                            echo "      ✓ Worktree created tracking remote branch: origin/$BRANCH_NAME"
                        elif [ -n "$PARENT_BRANCH" ] && git show-ref --verify --quiet "refs/heads/$PARENT_BRANCH" && \
                             git worktree add -b "$BRANCH_NAME" "$WORKTREE_PKG_PATH" "$PARENT_BRANCH" 2>/dev/null; then
                            echo "      ✓ Worktree created with new branch: $BRANCH_NAME (from parent $PARENT_BRANCH)"
                            PARENT_BRANCH_FOUND=true
                        elif [ -n "$PARENT_BRANCH" ] && git show-ref --verify --quiet "refs/remotes/origin/$PARENT_BRANCH" && \
                             git worktree add -b "$BRANCH_NAME" "$WORKTREE_PKG_PATH" "origin/$PARENT_BRANCH" 2>/dev/null; then
                            echo "      ✓ Worktree created with new branch: $BRANCH_NAME (from parent origin/$PARENT_BRANCH)"
                            PARENT_BRANCH_FOUND=true
                        elif [ -n "$REPOS_BRANCH" ] && \
                             git worktree add -b "$BRANCH_NAME" "$WORKTREE_PKG_PATH" "origin/$REPOS_BRANCH" 2>/dev/null; then
                            echo "      ✓ Worktree created with new branch: $BRANCH_NAME (from $REPOS_BRANCH)"
                        elif git worktree add -b "$BRANCH_NAME" "$WORKTREE_PKG_PATH" 2>/dev/null; then
                            echo "      ✓ Worktree created with new branch: $BRANCH_NAME"
                        else
                            # Fallback: attempt to use the package's current branch, then symlink on failure
                            CURRENT_BRANCH=$(git branch --show-current 2>/dev/null || true)
                            if [ -n "$CURRENT_BRANCH" ] && git worktree add "$WORKTREE_PKG_PATH" "$CURRENT_BRANCH" 2>/dev/null; then
                                echo "      ✓ Worktree created from current branch: $CURRENT_BRANCH"
                            else
                                echo "      ✗ Failed to create worktree for $pkg_name on branch: $BRANCH_NAME"
                                echo "      Falling back to symlink"
                                ln -s "$pkg_path" "$WORKTREE_PKG_PATH"
                            fi
                        fi
                        cd "$ROOT_DIR"
                    else
                        # Not a git repo, just symlink it
                        echo "      ! Not a git repo, symlinking instead"
                        ln -s "$pkg_path" "$WORKTREE_DIR/${LAYER_WS}/src/$pkg_name"
                    fi
                else
                    # Symlink to main for unmodified packages
                    echo "    - $pkg_name: symlinking to main"
                    ln -s "$pkg_path" "$WORKTREE_DIR/${LAYER_WS}/src/$pkg_name"
                fi
            done

            # Verify all requested packages were found
            for target_pkg in "${PACKAGE_ARRAY[@]}"; do
                if [ ! -e "$WORKTREE_DIR/${LAYER_WS}/src/$target_pkg" ]; then
                    echo "    ⚠️  Warning: Package '$target_pkg' not found in layer '$layer'"
                fi
            done
        else
            # Other layers - symlink to main
            if [ -d "$ROOT_DIR/layers/main/${LAYER_WS}" ]; then
                echo "  - $LAYER_WS: symlinking to main"
                ln -s "../../main/${LAYER_WS}" "$WORKTREE_DIR/${LAYER_WS}"
            fi
        fi
    done

    # If child branch already existed and --parent-issue was given, probe parent
    # branch existence in target package repos so draft PR can still target it.
    if [ -n "$PARENT_BRANCH" ] && [ "$PARENT_BRANCH_FOUND" = false ]; then
        for pkg_dir in "$WORKTREE_DIR"/"${TARGET_LAYER}_ws"/src/*; do
            [ -L "$pkg_dir" ] && continue
            [ ! -d "$pkg_dir/.git" ] && continue
            if git -C "$pkg_dir" show-ref --verify --quiet "refs/heads/$PARENT_BRANCH" || \
               git -C "$pkg_dir" show-ref --verify --quiet "refs/remotes/origin/$PARENT_BRANCH"; then
                PARENT_BRANCH_FOUND=true
                break
            elif fetch_remote_branch "$pkg_dir" "$PARENT_BRANCH" && \
                 git -C "$pkg_dir" show-ref --verify --quiet "refs/remotes/origin/$PARENT_BRANCH"; then
                PARENT_BRANCH_FOUND=true
                break
            fi
        done
    fi

    # Generate convenience scripts (setup.bash, build.sh, test.sh, etc.)
    generate_worktree_scripts "$WORKTREE_DIR" "$ROOT_DIR"
fi

# For workspace worktrees, symlink the layers directory
if [ "$WORKTREE_TYPE" == "workspace" ]; then
    echo ""
    echo "Setting up workspace worktree..."

    # Create symlink to main layers (using relative path for portability)
    # From: .workspace-worktrees/issue-N/layers/main
    # To:   layers/main (at root)
    # Path: ../../../layers/main (up through layers/ -> issue-N/ -> .workspace-worktrees/)
    echo "Creating symlink to main layers..."
    mkdir -p "$WORKTREE_DIR/layers"
    ln -s "../../../layers/main" "$WORKTREE_DIR/layers/main"

    # Ensure scratchpad exists
    mkdir -p "$WORKTREE_DIR/.agent/scratchpad"

    # Persist parent issue for worktree_enter.sh to pick up
    # Use scratchpad (gitignored) to avoid untracked file noise
    if [ -n "$PARENT_ISSUE_NUM" ]; then
        echo "$PARENT_ISSUE_NUM" > "$WORKTREE_DIR/.agent/scratchpad/.parent_issue"
    fi
fi

echo ""
echo "========================================"
echo "✅ Worktree Created Successfully"
echo "========================================"
if [ -n "$SKILL_NAME" ]; then
    echo "  Skill: $SKILL_NAME (ID: $SYNTHETIC_ID)"
elif [ -n "$ISSUE_TITLE" ]; then
    echo "  Issue #$ISSUE_NUM: $ISSUE_TITLE"
fi
[ -n "$PARENT_BRANCH" ] && echo "  Parent: #$PARENT_ISSUE_NUM ($PARENT_BRANCH)"
echo ""

# --plan-file: push branch, create draft PR, post plan as comment
if [ -n "$PLAN_FILE" ]; then
    if [ -n "$SKILL_NAME" ]; then
        echo "Creating draft PR for skill: $SKILL_NAME..."
    else
        echo "Creating draft PR for issue #$ISSUE_NUM..."
    fi
    echo ""

    # Use issue title fetched earlier; fall back to generic
    if [ -n "$SKILL_NAME" ]; then
        ISSUE_TITLE="Skill update: $SKILL_NAME"
    elif [ -z "$ISSUE_TITLE" ]; then
        echo "  ⚠️  Could not fetch issue title; using generic title"
        ISSUE_TITLE="Issue #$ISSUE_NUM"
    fi

    # Validate plan file exists
    HAS_PLAN=false
    if [ ! -f "$PLAN_FILE" ]; then
        echo "  ⚠️  Plan file not found: $PLAN_FILE (creating PR without plan comment)"
    else
        HAS_PLAN=true
    fi

    # Auto-detect agent identity if not already set in environment
    if [ -z "$AGENT_NAME" ] || [ -z "$AGENT_MODEL" ]; then
        if [ -f "$SCRIPT_DIR/framework_config.sh" ]; then
            source "$SCRIPT_DIR/framework_config.sh"
        fi
        if [ -f "$SCRIPT_DIR/detect_cli_env.sh" ]; then
            source "$SCRIPT_DIR/detect_cli_env.sh" || true
        fi
        if [ -n "$AGENT_FRAMEWORK" ] && [ "$AGENT_FRAMEWORK" != "unknown" ]; then
            FRAMEWORK_KEY="${AGENT_FRAMEWORK%-cli}"
            FRAMEWORK_KEY="${FRAMEWORK_KEY,,}"
            : "${AGENT_NAME:=${FRAMEWORK_NAMES[$FRAMEWORK_KEY]:-AI Agent}}"
            : "${AGENT_MODEL:=${FRAMEWORK_MODELS[$FRAMEWORK_KEY]:-Unknown}}"
        fi
    fi

    # Agent name/model for signatures — fall back to generic if still unset
    DRAFT_AGENT_NAME="${AGENT_NAME:-AI Agent}"
    DRAFT_AGENT_MODEL="${AGENT_MODEL:-Unknown}"

    # Helper: create a draft PR and optionally post the plan as a comment.
    # Arguments:
    #   $1 - git directory to push from
    #   $2 - issue reference (e.g. "#123" or "owner/repo#123")
    #   $3 - (optional) repo slug for gh pr create
    #   $4 - (optional) base branch for gh pr create
    create_draft_pr() {
        local git_dir="$1"
        local issue_ref="$2"
        local repo_flag="${3:-}"
        local base_flag="${4:-}"

        cd "$git_dir"

        # Push branch (empty commit if needed to create the remote ref)
        if ! git rev-parse --verify "origin/$BRANCH_NAME" &>/dev/null; then
            if [ -n "$issue_ref" ]; then
                git commit --allow-empty -m "chore: start work on $issue_ref" || true
            else
                git commit --allow-empty -m "chore: start skill update ($SKILL_NAME)" || true
            fi
        fi
        if ! git push -u origin "$BRANCH_NAME" 2>/dev/null; then
            echo "  ⚠️  Push failed — skipping draft PR (non-fatal)"
            return 1
        fi

        # Check if a PR already exists for this branch
        local existing_pr=""
        if [ -n "$repo_flag" ]; then
            existing_pr=$(gh pr list --repo "$repo_flag" --head "$BRANCH_NAME" --json url --jq '.[0].url' 2>/dev/null || echo "")
        else
            existing_pr=$(gh pr list --head "$BRANCH_NAME" --json url --jq '.[0].url' 2>/dev/null || echo "")
        fi
        if [ -n "$existing_pr" ]; then
            echo "  ℹ PR already exists: $existing_pr"
            # Post plan as comment on existing PR if available
            if [ "$HAS_PLAN" = true ]; then
                if gh pr comment "$existing_pr" --body-file "$PLAN_FILE" >/dev/null 2>&1; then
                    echo "  ✓ Plan posted as comment on existing PR"
                fi
            fi
            return 0
        fi

        # Create draft PR
        BODY_FILE=$(mktemp /tmp/gh_body.XXXXXX.md)
        if [ -n "$SKILL_NAME" ]; then
            cat > "$BODY_FILE" << PREOF
## Summary

$ISSUE_TITLE

Automated update from the \`$SKILL_NAME\` skill.

---
**Authored-By**: \`${DRAFT_AGENT_NAME}\`
**Model**: \`${DRAFT_AGENT_MODEL}\`
PREOF
        else
            if [ -n "$PLAN_FILE" ]; then
                cat > "$BODY_FILE" << PREOF
## Summary

$ISSUE_TITLE

Plan for $issue_ref

Closes $issue_ref
PREOF
            else
                cat > "$BODY_FILE" << PREOF
## Summary

$ISSUE_TITLE

Closes $issue_ref
PREOF
            fi
            # Add parent issue reference if creating a sub-issue worktree
            # Use same cross-repo resolution as issue_ref (owner/repo#N vs #N)
            if [ -n "$PARENT_ISSUE_NUM" ]; then
                if [[ "$issue_ref" == */* ]]; then
                    # Cross-repo: extract owner/repo prefix from issue_ref
                    _parent_ref="${issue_ref%%#*}#${PARENT_ISSUE_NUM}"
                else
                    _parent_ref="#${PARENT_ISSUE_NUM}"
                fi
                echo "Part of $_parent_ref" >> "$BODY_FILE"
            fi
            cat >> "$BODY_FILE" << PREOF

---
**Authored-By**: \`${DRAFT_AGENT_NAME}\`
**Model**: \`${DRAFT_AGENT_MODEL}\`
PREOF
        fi

        local pr_title="$ISSUE_TITLE"
        if [ -n "$PLAN_FILE" ]; then
            pr_title="[PLAN] $ISSUE_TITLE"
        fi
        local gh_args=(pr create --draft --title "$pr_title" --body-file "$BODY_FILE")
        [ -n "$repo_flag" ] && gh_args+=(--repo "$repo_flag")
        [ -n "$base_flag" ] && gh_args+=(--base "$base_flag")

        GH_STDERR=$(mktemp /tmp/gh_stderr.XXXXXX)
        local pr_url
        pr_url=$(gh "${gh_args[@]}" 2>"$GH_STDERR") && PR_CREATED=true || PR_CREATED=false

        if [ "$PR_CREATED" = true ]; then
            echo "  ✓ Draft PR created: $pr_url"
            # Post plan as PR comment
            if [ "$HAS_PLAN" = true ]; then
                if gh pr comment "$pr_url" --body-file "$PLAN_FILE" >/dev/null 2>&1; then
                    echo "  ✓ Plan posted as PR comment"
                else
                    echo "  ⚠️  Failed to post plan comment (non-fatal)"
                fi
            fi
        else
            echo "  ⚠️  Draft PR creation failed (non-fatal)"
            cat "$GH_STDERR" >&2
        fi
        rm -f "$GH_STDERR" "$BODY_FILE"
    }

    # Only use parent branch as PR base if it was actually found during worktree creation
    PR_PARENT_BASE=""
    if [ "$PARENT_BRANCH_FOUND" = true ]; then
        PR_PARENT_BASE="$PARENT_BRANCH"
    fi

    if [ "$WORKTREE_TYPE" == "workspace" ]; then
        if [ -n "$SKILL_NAME" ]; then
            create_draft_pr "$WORKTREE_DIR" ""
        else
            create_draft_pr "$WORKTREE_DIR" "#$ISSUE_NUM" "" "$PR_PARENT_BASE"
        fi
        cd "$ROOT_DIR"

    elif [ "$WORKTREE_TYPE" == "layer" ]; then
        for pkg_dir in "$WORKTREE_DIR"/"${TARGET_LAYER}_ws"/src/*; do
            # Skip symlinks (unmodified packages) and non-git dirs
            [ -L "$pkg_dir" ] && continue
            [ ! -e "$pkg_dir/.git" ] && continue

            pkg_name=$(basename "$pkg_dir")
            echo "  Creating draft PR for package: $pkg_name"

            # Determine repo slug from remote
            PKG_REMOTE_URL=$(git -C "$pkg_dir" remote get-url origin 2>/dev/null || echo "")
            PKG_REPO_SLUG=""
            if [ -n "$PKG_REMOTE_URL" ]; then
                PKG_REPO_SLUG=$(extract_gh_slug "$PKG_REMOTE_URL")
            fi

            # Build issue reference — skip in skill mode (no issue to close)
            if [ -n "$SKILL_NAME" ]; then
                ISSUE_REF=""
            elif [ -n "$GH_REPO_SLUG" ] && [ -n "$PKG_REPO_SLUG" ] && [ "$GH_REPO_SLUG" != "$PKG_REPO_SLUG" ]; then
                ISSUE_REF="$GH_REPO_SLUG#$ISSUE_NUM"
            else
                ISSUE_REF="#$ISSUE_NUM"
            fi

            # Resolve the .repos base branch for the PR target
            # Parent branch takes priority, but verify it exists in this package repo
            PKG_BASE_BRANCH=""
            if [ "$PARENT_BRANCH_FOUND" = true ]; then
                fetch_remote_branch "$pkg_dir" "$PARENT_BRANCH" || true
                if git -C "$pkg_dir" show-ref --verify --quiet "refs/remotes/origin/$PARENT_BRANCH" || \
                   git -C "$pkg_dir" show-ref --verify --quiet "refs/heads/$PARENT_BRANCH"; then
                    PKG_BASE_BRANCH="$PARENT_BRANCH"
                fi
            fi
            if [ -z "$PKG_BASE_BRANCH" ]; then
                PKG_BASE_BRANCH=$(resolve_repos_branch "$pkg_name")
            fi

            create_draft_pr "$pkg_dir" "$ISSUE_REF" "$PKG_REPO_SLUG" "$PKG_BASE_BRANCH"
        done
        cd "$ROOT_DIR"
    fi

    echo ""
fi

if [ -n "$SKILL_NAME" ]; then
    echo "To enter this worktree:"
    echo "  source $SCRIPT_DIR/worktree_enter.sh --skill $SKILL_NAME"
    echo ""
    echo "Or manually:"
    echo "  cd $WORKTREE_DIR"
    if [ "$WORKTREE_TYPE" == "layer" ]; then
        echo "  source setup.bash                    # Set up ROS environment"
        echo "  cd ${TARGET_LAYER}_ws && ./build.sh  # Build"
    fi
    echo ""
    echo "When done, remove with:"
    echo "  $SCRIPT_DIR/worktree_remove.sh --skill $SKILL_NAME"
else
    echo "To enter this worktree:"
    echo "  source $SCRIPT_DIR/worktree_enter.sh --issue $ISSUE_NUM"
    echo ""
    echo "Or manually:"
    echo "  cd $WORKTREE_DIR"
    if [ "$WORKTREE_TYPE" == "layer" ]; then
        echo "  source setup.bash                    # Set up ROS environment"
        echo "  cd ${TARGET_LAYER}_ws && ./build.sh  # Build"
    fi
    echo ""
    echo "When done, remove with:"
    echo "  $SCRIPT_DIR/worktree_remove.sh --issue $ISSUE_NUM"
fi
